language: node_js
sudo: false
node_js:
- 6
- 8
script:
- npm run ci
- chmod 777 ./node_modules/@pearson-components/npm-scripts/shell_scripts/run_selenium_ci_tests.sh
- export TEST_GROUP=desktop-regression
- ./node_modules/@pearson-components/npm-scripts/shell_scripts/run_selenium_ci_tests.sh
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: sWG86pGD0vc7NTEBYwMRA11mooAc438/FS9D0C1V+WB9zGzsPPJiRdZVGRlGPYsNpDmgTlS2znqThx61npTmAOExm2/f7fLUShdmSwv3a2Hk7wpInemzR6jGbg2raMGkhovoy0BvilQnjVWV2Qp9tEO8mWQHTRtWbCeNK0JhcxnrKqTBZkA7+pNr7GEO7nI+wp2X7Eqc2FGsaXHLWNmp6rXwuHFq6lprFKMpg0iygFrfoYVVW0xLAobkYsyTBSFvblYpiXuIU39mV5j/7WgjsYmYyEr5ed1dkiBy1UZy1kDhi7MsRdGCGm2LqhsRbJhCWArWzoEXw+LSWcC/R4+BYzDPVtd/rWCfsX09yV/vkMuu/Yh+ZdDXL/s0j0uUkXcgRZ9z4KThaNmzjeaoDjQNkG+48e5/JCGwPRKGkYCnOf5BGjRgVf8EK2x8K6ogVPV/r4z5QWuTl3u9iA+5W7hb8lB/8u9F26RdYtpy3SFDd5bmE8LgJfDn5kvm02ZSsjxHLMplS3k0E793eiPyTwS+alORFXme1dyt+zhaA6NbYrOy6l6frHS6TV+ypghCN8sZ26X/jO/5kSZbRb6L3IHffRIbaId5BWbQesM2uzUqSMR+7rThKDc9BSGjOn7T5mOUFCED9r/OUYtzkBtcRYQ+jKDuq6C+lmJLIuO+IJt8zY4=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
  - secure: Q5WWgkc0DA9S9pZh+RmTOVYtV0jWKqsi5c2CFMk/vzzvMsszpbILdZqkRINJxad6x6SRyhkzx7Ru65VRL4LAgoM8wc9GCQKYGn1KJiu3lsXZOcb/VrxmOo6pr75kJddbX5UYHL+vQ9euOGTyJvQjMDAbow6myqEYT+SKVAeq0ybMZVc0Oy0+jT/QHsTe8KP/zQukSlMgWSdGJLRVvB+alkskYehBr8L3Rtutxmszjzv9xMZjuUFuKd7Xen9KMLMHf2WiDP6O/i7dzcpbspO2IZ4l5Av8i1UaxX41NQ8pncXlcUELLuRRAZKD5oANmBHjLjBNTGIetEmM9+dIKygdt0wAHExtWxJ1Mk+ABkNXKvZrDtdPDsnGMxAJ6jdDe+kFuE97hDeHgryS7MIl2DoWlXGGhd1+K0dETGk7oeUpzASioN/WjX5IfKNJzcvhNCO6sXsh6nPM0T22tkovnZ3N1uplKvisw/zPlOs/WpxirP3aC5Lfi7QNpNmWBgg8s720YlBmDm8EoxYkfDP7bN+6UrAfLedvFOUJxZaqV43EAoN66inBGzK/Q0kRpR9NJ0PIMpw3sf1unDe/mV5xU+SvDUUgrVfx9RhUjsSmohK680zTWb84+mz9hV4SiG4wi/weVejG374U+OHfw8cqoPSJ1HKC9U2rOtviLzkGa5oxGH8=
addons:
  sonarqube:
    organization: ''
    token:
      secure: sWHEElq3q9Nv+u8SrEN5sqpyPC9+PmxXjMzjbByW13e4oMJ9aQd/KtrVz4xU7QjeNK9Jkx5hHHE6dT88q6JSg2Jfwo09dX8EwLsu/KYDqFkGEI3f0uWWWVBdNeTxcexOzdQb44GomAljTLvp7tsorS1kgWHtRhq0y4fXNIjG3eqWQJsgNoUzjEaM5fGAQmWx8FHgL+cFeIcomRpmwv0gCFKcrxSPlaZgysNBriVwHebzubmpChdr25Cr5/fJbpA699o8OBUti4L6b7dwsf2WlS2jH/0J5AQ2Cu5oDaJzajsBqHAYqcoIwcfxNpYOkIKiL4lHHWNdIEywmvAygvl2TCLORIvGUcZB2W8n1cC7p/62zFwFfxkLxdjQxEPDExNErWjrznSyUY/D+qy0QU9afLAGAPZ5bgIEa+Qd7osChDfjRGMRtfFAY4vJNKlxHu5SHg0L0GVqWkd5rn4Lv7pPHlyWXmBdiN84za52l4EKw5gA84FCInxJBvb4+4TVc+BFz/joPNuAEnDwZeRf2teVs92oMm7Uk+27aJ48sadk7ky/Nc+67qnCqrAjnZEoPUlDIy7s58SDwHHbq3x/ST5mY0uWRux6NRaMWzdRfOw/mx0BHkNjWOGnzsy6PhrnhOxJ7MFg7p2i+N+FXbaX2c1R3CcMe2QcNFfLncvXSXQNeW4=
